"""
Echo runtime: dry-run agent that writes deterministic output files.

Used for E2E testing of the full pipeline (router -> Docker -> entrypoint ->
storage) without requiring any API keys. Reads the instruction, extracts
expected output filenames, and generates stub content for each.

This runtime is NOT for production — it's a testing shim.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


class EchoRuntime:
    """
    Testing-only runtime that produces deterministic output files.
    Extracts expected filenames from the instruction and writes stub content.
    """

    def __init__(self, **kwargs):
        pass

    async def execute(
        self,
        prompt: str,
        skills_dir: Path | None,
        output_dir: Path,
        *,
        max_turns: int = 30,
    ) -> str:
        print(f"\n--- Echo Runtime (dry-run) ---")
        print(f"  Output dir: {output_dir}")

        output_dir.mkdir(parents=True, exist_ok=True)

        # Extract filenames mentioned in the prompt (e.g. "company_profile.md")
        filenames = re.findall(r'\b([\w\-]+\.(?:md|json|txt|csv|yaml|yml))\b', prompt)
        # Deduplicate preserving order
        seen = set()
        unique_files = []
        for f in filenames:
            if f not in seen:
                seen.add(f)
                unique_files.append(f)

        if not unique_files:
            unique_files = ["output.md"]

        written = []
        for filename in unique_files:
            filepath = output_dir / filename
            if filename.endswith(".json"):
                content = json.dumps({
                    "source": "echo-runtime",
                    "instruction_preview": prompt[:200],
                    "status": "dry-run",
                }, indent=2)
            elif filename.endswith(".md"):
                content = (
                    f"# Echo Output: {filename}\n\n"
                    f"This file was generated by the echo runtime (dry-run mode).\n\n"
                    f"## Instruction\n{prompt[:500]}\n"
                )
            else:
                content = f"Echo output for {filename}\nInstruction: {prompt[:200]}\n"

            filepath.write_text(content, encoding="utf-8")
            written.append(filename)
            print(f"  [ECHO] Wrote: {filename} ({len(content)} bytes)")

        summary = f"Echo runtime completed. Wrote {len(written)} files: {', '.join(written)}"
        print(f"\n  {summary}")
        return summary
